### ISSUE TITLE
Error when calling Disconnect on already closed connection

### ISSUE THREAD

**Issue by Sir-Will** [xrjr/mcutils#10]
Hey,

I'm getting the following error when calling `pingclient.Disconnect()` when the connection was already closed.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x668b98]

goroutine 80565 [running]:
github.com/xrjr/mcutils/pkg/ping.(*PingClient).Disconnect(0xc000ef5f68)
        /go/src/gocode/vendor/github.com/xrjr/mcutils/pkg/ping/client.go:197 +0x18
main.retrieveMinecraft({0xc000239734, 0x66c38d}, 0x0)
        /go/src/gocode/cmd/main/main.go:114 +0x2f7
created by main.queryServers.func1
        /go/src/gocode/cmd/main/main.go:182 +0x1ef
 ```

**Comment by xrjr** [comment]
Thank you for your feedback, #11 should fix this behavior on all clients.

**Comment by Sir-Will** [comment]
Thanks.
